module ApplicationHelper
  def academic_periods
    ['', '2017-2018 Academic Year', 'Fall 2017', 'Winter 2018', 'Spring 2018', 'Summer 2018']
  end

  def graduation_periods(application_type=nil)
      years = nil
      if application_type == "student_loan"
         years = (2018..2022)
      else
         years = (1995..2022)
      end

      periods = []
      years.each do |year|
         ['Winter', 'Spring', 'Summer'].each do |season|
            periods << "#{season} #{year}"
         end
      end
      periods.unshift('')
      periods
  end

  def email_url(url, campaign=nil)
    "#{url}?utm_campaign=#{campaign}&utm_medium=email" 
  end

  def application_type_priority(application_type)
   case application_type
    when "student_loan"
      then 1
    when "auto_loan"
      then 2
    when "credit_card"
      then 3
    else 10
    end
  end

  def display_pricing(pricing,with_decimals=false, with_symbol=false)
      if pricing
         pricing = 0 if pricing.nil?
         pricing = number_with_precision(pricing, :precision => 2, :delimiter => ',')
         pricing = pricing.to_s.split(".")
         str = ""
         if with_symbol
            str += "$"
         end

         str += "#{pricing[0]}"

         if with_decimals
           str += ".#{pricing[1].ljust(2,'0')}"
         end

         return str
      else
         nil
      end
  end

   def us_states
      [
      ['', ''],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
      ]
   end

  def degrees
    { "Undergraduate" =>  ["Bachelors", "Other"], "Graduate" => ["MS: Engineering or Information Science or Computer Science", "MBA", "Law", "Masters Public Policy", "Doctorate", "Other Graduate"]}
  end

  def countries
    ["", "Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Barbuda", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Trty.", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Caicos Islands", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo, Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories", "Futuna Islands", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard", "Herzegovina", "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Jan Mayen Islands", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea", "Korea (Democratic)", "Kuwait", "Kyrgyzstan", "Lao", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "McDonald Islands", "Mexico", "Micronesia", "Miquelon", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "Nevis", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Principe", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Barthelemy", "Saint Helena", "Saint Kitts", "Saint Lucia", "Saint Martin (French part)", "Saint Pierre", "Saint Vincent", "Samoa", "San Marino", "Sao Tome", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia", "South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "The Grenadines", "Timor-Leste", "Tobago", "Togo", "Tokelau", "Tonga", "Trinidad", "Tunisia", "Turkey", "Turkmenistan", "Turks Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "US Minor Outlying Islands", "Uzbekistan", "Vanuatu", "Vatican City State", "Venezuela", "Vietnam", "Virgin Islands (British)", "Virgin Islands (US)", "Wallis", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"]
  end

  def universities
    [
      "",
"Still Deciding",
"School Not Listed",
"A. J. Institute of Management - Mangalore",
"ABES Engineering College - Ghaziabad",
"Abilene Christian University",
"ABS Academy - Durgapur",
"ABSS Institute of Technology - Meerut",
"Academy of Business Administration - Balasore",
"Accman Institute of Management - Greater Noida",
"Accurate Institute of Management - Greater Noida",
"Acharya Bangalore Business School - Bangalore",
"Acharya Institute of Management and Sciences - Bangalore",
"Acliv Technology and Management Academy (ATMA) - Bangalore",
"Acropolis Faculty of Management and Research  - Indore",
"Acropolis Technical Campus - FMS - Indore",
"Adam's Engineering College - Khammam ",
"Adani Institute of Infrastructure Management - Ahmedabad",
"Adarsh Business School - Bangalore",
"Adarsh Institute of Management and Information Technology - Bangalore",
"Adelphi University",
"Adharshila College of Education - Meerut",
"Aditya Institute of Management Studies and Research - Mumbai",
"Administrative Management College - Bangalore",
"Aegis School of Business and Telecommunication - Navi Mumbai",
"Agnes Scott College",
"Agriculture & Food Management Institute - Mysore",
"AGSM at UNSW Business School",
"AICAR Business School - Raigad",
"Air Force Institute of Technology",
"AJ Institute of Management - Mangalore",
"Ajay Kumar Garg Institute of Management  - Ghaziabad",
"Akemi Business School - Pune",
"Alabama A&M University",
"Alabama State University",
"Alaska Pacific University",
"Albertson College of Idaho",
"Albion College",
"Alderson Broaddus College",
"Alfred University",
"Allana Institute of Management Science - Pune",
"Allegheny College",
"Allentown College of Saint Francis de Sales",
"Alliance Manchester Business School",
"Alliance School of Business - Bangalore",
"Alma College",
"Alverno College",
"Ambassador University",
"Ambedkar Institute of Management Studies - Vishakhapatnam",
"AMC Engineering College  - Bangalore",
"American Coastline University",
"American Graduate School of International Management",
"American International College",
"American University",
"American University of India - Madurai",
"Amherst College",
"Amity Business School - Noida",
"Amity Global Business School - Ahmedabad",
"Amity Institute of Telecom Technology and Management - New Delhi",
"Amity International Business School - Noida",
"Amity School of Fashion Technology - Noida",
"Amrita School of Business  - Coimbatore",
"Amrita School of Business - Bangalore",
"Amrut Mody School of Management - Ahmedabad",
"AMS School of Informatics - Hyderabad",
"Andrews University",
"Anekant Institute of Management Studies - Baramati",
"Angelo State University",
"Ansal University - Gurgaon",
"Antioch College",
"Antioch New England",
"Antioch University - Los Angeles",
"Antioch University - Seattle",
"Apeejay Institute of Technology - Noida",
"Apeejay School of Management - Delhi",
"Apoorva Institute Of Management And Sciences - Karimnagar",
"Appalachian State University",
"Aquinas College",
"AR School of Business - DINDIGUL",
"Arizona State University",
"Arizona State University - East",
"Arizona State University - West",
"Arizona Western College",
"Arkansas State University - Jonesboro",
"Arkansas Tech University",
"Armstrong State College",
"Army Institute of Management - Kolkata",
"Army Institute of Management & Technology  - Noida",
"Asbury University",
"Ashland University",
"Asia Pacific Institute of Information Technology - Panipat",
"Asian Business School - Noida",
"Asian School of Business - Thiruvananthapuram",
"Asian School of Business Management - Bhubaneswar",
"Asian Workers Development Institute - Rourkela",
"Assumption College",
"Astha School of Management - Bhubaneswar",
"Atharva Institute of Management Studies - Mumbai",
"Athens State College",
"ATM Global Business School - Delhi",
"Auburn University",
"Auburn University - Montgomery",
"Audyogik Shikshan Santha's Institute of Management and Computer Studies - Mumbai",
"Augsburg College",
"Augustana College (IL)",
"Augustana College (SD)",
"Auro University  - Surat",
"Aurora University",
"Aurora's Business School - Hyderabad",
"Austin College",
"Austin Peay State University",
"Averett College",
"Avidus Academy of Management  - Chennai",
"Avila College",
"Azusa Pacific University",
"Babson College",
"Babu Banarsi Das Institute of Technology - Ghaziabad",
"Baker University",
"Balaji Institute of International Business - Pune",
"Balaji Institute of Management and Human Resource Development - Pune",
"Balaji Institute of Telecom and Management - Pune",
"Baldwin Wallace College",
"Baldwin Wallace University",
"Ball State University",
"Bangalore Institute of International Management - Bangalore",
"Bangalore Institute of Management Studies  - Bangalore",
"Baptist Bible College",
"Bard College",
"Barry University",
"Bastyr University",
"Bates College",
"Baylor College of Medicine",
"Baylor University",
"BDS Institute of Management - Meerut",
"Beaver College",
"Bellarmine University",
"Belmont University",
"Beloit College",
"Bemidji State University",
"Benedictine College",
"Bengal Institute of Business Studies  - Kolkata",
"Bennington College",
"Bentley College",
"Berea College",
"Berklee College of Music",
"Berlin School of Creative Leadership",
"Berry College",
"Bethany College (CA)",
"Bethany College (WV)",
"Bethel College (KS)",
"Bethel College and Seminary (MN)",
"Bhai Gurdas Institute of Management & Technology - Sangrur",
"Bhai Parmanand Institute of Business Studies - Delhi",
"Bharatesh Education Trust's Global Business School - Belgaum",
"Bharathidasan Institute of Management - Trichy",
"Bharatiya Vidya Bhavan's Usha & Lakshmi Mittal Institute of Management - Delhi",
"Bhavdiya Institute of Business Management - Faizabad",
"BIMT - Gurgaon",
"Biola University",
"Birla Institute of Management Technology  - Bhubaneswar",
"Birla Institute of Management Technology - Greater Noida",
"Birla Institute of Technology & Science - Pilani",
"Birmingham - Southern College",
"Birmingham Business School",
"Birsa Institute of Technology - Ranchi",
"Biyani Institute of Science & Management  - Jaipur",
"Black Hills State University",
"Bloomsburg University of Pennsylvania",
"Bluffton College",
"BM Group of Technology and Managment  - Gurgaon",
"Bob Jones University",
"Boise State University",
"Boston College",
"Boston Graduate School of Psychoanalysis",
"Boston University",
"Bowdoin College",
"Bowie State University",
"Bowling Green State University",
"Bradley University",
"Brandeis University",
"Brenau University",
"Briar Cliff College",
"Bridgewater College",
"Brigham Young University",
"Brigham Young University - Hawaii",
"BRM Institute of Management & Information Technology  - Bhubaneswar",
"Brown University",
"Bryant College",
"Bryant University",
"Bryn Mawr College",
"Bucknell University",
"Buena Vista University",
"Butler University",
"California Coast University",
"California Institute of Technology",
"California Lutheran University",
"California Maritime Academy",
"California National University",
"California Pacific University",
"California Polytechnic State University - San Luis Obispo",
"California School of Professional Psychology",
"California State Polytechnic University - Pomona",
"California State University - Bakersfield",
"California State University - Chico",
"California State University - Dominguez Hills",
"California State University - Fresno",
"California State University - Fullerton",
"California State University - Hayward",
"California State University - Long Beach",
"California State University - Los Angeles",
"California State University - Monterey Bay",
"California State University - Northridge",
"California State University - Sacramento",
"California State University - San Bernardino",
"California State University - San Jose ",
"California State University - San Marcos",
"California State University - Stanislaus",
"California State University System",
"California University of Pennsylvania",
"Calvin College",
"Cameron University",
"Campbell University",
"Campbellsville College",
"Canisius College",
"Career Point University - Hamirpur",
"Career Point University - Kota",
"Carleton College",
"Carlow College",
"Carnegie Mellon University",
"Carroll College (MT)",
"Carroll College (WI)",
"Carson Newman College",
"Carthage College",
"Case Western Reserve University",
"Castleton State University",
"Catalyst Institute of Management and Advance Global Excellence  - Patna",
"CBM College - Coimbatore",
"CBS College of Engineering and Management - Agra",
"Cedarville College",
"CEIBS",
"Centenary College of Louisiana",
"Center for Management Studies - Bangalore",
"Center for Management Studies - Bhubaneswar",
"Central College",
"Central Connecticut State University",
"Central Institute of Business Management Research & Development  - Nagpur",
"Central Methodist College",
"Central Michigan University",
"Central Missouri State University",
"Central University of Jammu  - Jammu",
"Central Washington University",
"Centre College",
"Centre for Management - Mumbai",
"Centre for Management Development  - Ghaziabad",
"Centre For Management Training & Research  - Mohali",
"Centurion University of Technology and Management - Bhubaneswar",
"CET school of Management - Thiruvananthapuram",
"CH Institute of Management and Communication  - Indore",
"Chadron State College",
"Chaitanya Bharathi Institute of Technology  - Hyderabad",
"Champlain College",
"Chandigarh Business School of Administration - Mohali",
"Chandigarh Group of Colleges - Greater Mohali",
"Chandigarh Group of Colleges -Jhanjeri (CGC Jhanjeri) ",
"Chandigarh University  - Chandigarh",
"Chandragupt Institute of Management  - Patna",
"Chapman University",
"Chatham College",
"Chennai Business School  - Chennai",
"Chesapeake College",
"Cheyney University",
"Chinese University of Hong Kong  - CUHK Business School",
"Chitkara Business School - Rajpura",
"Christ University  - Bangalore",
"Christhu Raj College  - Tiruchirappalli",
"Christian Brothers University",
"Christian Theological Seminary",
"Christopher Newport University",
"City University",
"City University of New York",
"CK Pithawalla Institute of Management - Surat",
"Claremont Graduate School",
"Claremont McKenna College",
"Clarion University of Pennsylvania",
"Clark University",
"Clarke College",
"Clarkson University",
"Clayton State College",
"Clemson University",
"Cleveland State University",
"Clinch Valley College",
"CMR Institute of Management Studies - Bangalore",
"Coastal Carolina University ",
"Coe College",
"Coimbatore Institute of Management - Coimbatore",
"Coker College",
"Colby College",
"Colgate University",
"College of Charleston",
"College of Commerce - Shivaji University - Pune ",
"College of Eastern Utah",
"College of New Jersey",
"College of Saint Benedict",
"College of Saint Catherine",
"College of Saint Rose",
"College of St. Francis",
"College of St. Scholastica",
"College of the Atlantic",
"College of the Holy Cross",
"College of William and Mary",
"Colorado Christian University",
"Colorado College",
"Colorado School of Mines",
"Colorado State University",
"Columbia College Chicago",
"Columbia Southern University",
"Columbia Union College",
"Columbia University",
"Compucom Institute of Information Technology & Management  - Jaipur",
"Concordia College - Ann Arbor",
"Concordia College - Moorhead",
"Concordia College - Seward",
"Concordia College - St. Paul",
"Concordia University River Forest - Illinois",
"Connecticut College",
"Coppin State College",
"Core Business School  - Indore",
"Cornell College",
"Cornell University",
"Cornerstone College",
"Cosmic Business School  - Delhi",
"Cranfield School of Management",
"Cranfield University",
"Creighton University ",
"Crescent Business School - B.S.Abdur Rahman University - Chennai",
"Curry CollegeD",
"Daemen College",
"Dakota State University",
"Dakota Wesleyan University",
"Dallas Baptist University",
"Dana College",
"Daniel Webster College",
"Dartmouth College",
"Davenport College Detroit College of Business",
"Davidson College",
"Davis & Elkins College",
"Dayanand Academy of Management Studies  - Kanpur",
"Dayananda Sagar College of Management - Bangalore",
"DC School of Management and Technology - Idukki",
"DCSMAT Business School  - Vagamon",
"DE Society's Institute of Management Development & Research - Pune",
"Deen Dayal College of Management  - Muzaffarnagar",
"Delaware State University",
"Delhi Business School - Delhi",
"Delhi Institute of Higher Education  - Delhi",
"Delhi School of Business  - Delhi",
"Delhi School of Professional Studies and Research  - Delhi",
"Delta State University",
"Denison University",
"Department of Business Administration and Research - Shri Sant Gajanan Maharaj College of Engineering - Buldana",
"Department of Business Management - H.N.B Garhwal University - Garhwal",
"Department of Business Management - University of Calcutta",
"Department of Commerce - Delhi School of Economics - University of Delhi",
"Department of Financial Studies - University of Delhi - South Campus",
"Department of Industrial and Management Engineering - Indian Institute of Technology Kanpur",
"Department of Management & Administration - Manav Rachna College of Engineering - Faridabad",
"Department of Management Studies - Indian Institute of Science Bangalore",
"Department of Management Studies - Indian Institute of Technology - Delhi",
"Department of Management Studies - Indian Institute of Technology Madras",
"Department of Management Studies - Indian Institute of Technology Roorkee",
"Department of Management Studies - Pondicherry University - Pondicherry",
"Department of Management Studies - Virudhunagar Hindu Nadars' Senthikumara Nadar College - Virudhunagar",
"DePaul University",
"DePauw University",
"Dev Bhoomi Group of Institutions - Saharanpur",
"DeVry Institute of Technology",
"DeVry Institute of Technology - Dallas",
"DeVry Institute of Technology - Phoenix",
"Dhruva College of Management - Hyderabad",
"Dickinson College",
"Dickinson State University",
"Dillard University",
"Disha Institute of Management and Technology - Raipur",
"DIT School of Business  - Noida",
"DIT University  - Dehradun",
"DJ College of Engineering and Technology  - Ghaziabad",
"DNS College of Engineering and Technology  - Amroha",
"Dnyansagar Institute of Management and Research  - Pune",
"Dominican College",
"Don Bosco Institute of Management - Guwahati",
"Doon Business School - Dehradun",
"Doraha Institute of Management & Technology  - Ludhiana",
"Dordt College",
"Dowling College",
"Dr Gaur Hari Singhania Institute of Management  - Kanpur",
"Dr I T School of Management  - Chandigarh",
"Dr KN Modi University - Newai",
"Dr M C Saxena Group of Colleges - Lucknow",
"Dr Nagamani Sivayya Kolla School of Business - Vishakhapatnam",
"Dr. Panjabrao Deshmukh Institute of Management Technology and Research - Nagpur",
"Dr. VN Bedekar Institute of Management Studies - Thane",
"Drake University",
"Drew University",
"Drexel University",
"Dronacharya Group of Institutions  - Noida",
"Dronacharya Institute of Management & Technology  - Kurukshetra",
"Drury College",
"Drury University",
"Duke University",
"Duquesne University",
"Durgadevi Saraf Institute of Management Studies  - Mumbai",
"Durham University Business School",
"Earlham College",
"East Carolina University",
"East Central University",
"East Stroudsburg State University of Pennsylvania",
"East Tennessee State University",
"East Texas State University",
"Eastern Connecticut State University",
"Eastern Illinois University",
"Eastern Institute for Integrated Learning in Management  - Kolkata",
"Eastern Kentucky University",
"Eastern Mennonite University",
"Eastern Michigan University",
"Eastern Nazarene College",
"Eastern New Mexico University",
"Eastern Oregon State College",
"Eastern University",
"Eastern Washington University",
"Edgewood College",
"Edhec Business School",
"Edify Institute of Management & Technology  - Mathura",
"Edinboro University of Pennsylvania",
"Elizabeth City State University",
"Elizabethtown College",
"Elmhurst College",
"Elon College",
"Elon University",
"Embry-Riddle Aeronautical University - Arizona",
"Embry-Riddle Aeronautical University - Florida",
"Emerson College",
"Emmanuel College",
"Emmaus Bible College",
"Emory and Henry College",
"Emory University",
"Emporia State University",
"Entrepreneurship and Management Process International Business School  - Delhi",
"Entrepreneurship Development Institute of India - Gandhinagar",
"ESADE Business School",
"Europe Asia School of Business - Pune ",
"European School of Management and Technology",
"Evergreen State College",
"Ewing Christian Institute of Management & Technology - Allahabad",
"Excel Business Academy  - Bangalore",
"Faculty of Management - EBET Group of Institutions - Tirupur",
"Faculty of Management Studies - Banaras Hindu University",
"Faculty of Management Studies - Manav Rachna International University - Faridabad",
"Faculty of Management Studies - University of Delhi - Delhi",
"Faculty of Management Studies - Veer Bahadur Singh Purvanchal University - Jaunpur",
"Faculty of Management Studies (FMS) - Gurukula Kangri Vishwavidyalaya - Haridwar",
"Facutly of Management Studies - Baroda",
"Fairfield University",
"Fairleigh Dickinson University",
"Fairmont State College",
"Fayetteville State University",
"Ferris State University",
"Fielding Institute",
"Fisk University",
"Fitchburg State College",
"Flame School of Business  - Pune",
"Florida Agricultural and Mechanical University",
"Florida Atlantic University",
"Florida Gulf Coast University",
"Florida Institute of Technology",
"Florida International University",
"Florida Southern College",
"Florida State University",
"Fontbonne College",
"Fordham University",
"FORE School of Management - New Delhi",
"Fort Hays State University",
"Fort Lewis College",
"Fortune Institute of International Business - Delhi",
"Fostiima Business School - Delhi",
"Francis Xavier Dept. of Management Studies - Tirunelveli",
"Franciscan University",
"Franklin and Marshall College",
"Franklin Pierce Law Center",
"Franklin University ",
"Fresno Pacific University",
"Friends University",
"Frostburg State University",
"Fudan University School of Management",
"Fuller Theological Seminary",
"Furman University",
"G. H. Patel Postgraduate Institute of Business Management - Vidyanagar",
"Galgotias Business School - Uttar Pradesh - Greater Nodia",
"Gallaudet University",
"Gandhi Institute of Management Studies - Rayagada",
"Ganga Group of Institutions  - Delhi",
"Gannon University",
"Gayatri International Institute of Planning & Management  - Noida",
"GCRG Group of Institution - Lucknow",
"GEM Business Academy - Erode",
"Geneva College",
"George Fox College",
"George Mason University",
"George Washington University",
"Georgetown University",
"Georgia College",
"Georgia Institute of Technology",
"Georgia Southern University",
"Georgia Southwestern College",
"Georgia State University",
"Georgian Court College",
"Gettysburg College",
"GIBS Business School  - Bangalore",
"GITAM School of International Business  - Vishakhapatnam",
"GL Bajaj Institute of Management and Research - Greater Noida",
"Global Business School - Hubli",
"Global Education Centre - Hyderabad",
"Global Institute of Management  - Bhubaneswar",
"Global Institute of Technology & Management - Gurgaon",
"GMI Engineering and Management Institute",
"Gnanam School of Business  - Coimbatore",
"GNVS Institute of Management  - Mumbai",
"Goa Institute of Management - Goa",
"Goel Group of Institutions  - Lucknow",
"Gogte Institute of Technology - Belgaum",
"Golden Gate University",
"Goldey-Beacom College",
"Gonzaga University",
"Goshen College",
"Goucher College",
"Governors State University",
"Govindram Seksaria Institute of Management & Research - Indore",
"Grace College",
"Graceland College",
"Grand Valley State University",
"Great Lakes Institute of Management - Chennai",
"Greenleaf University",
"Grenoble Ecole de Management",
"GRG School of Management Studies - Coimbatore",
"Grinnell College",
"Guilford College",
"Guru Nanak Institute of Management  - Delhi",
"Guru Nanak Institute of Management and Technology  - Ludhiana",
"Guruvayurappan Institute of Management  - Coimbatore",
"Gustavus Adolphus College",
"Gutenberg College",
"H. K. Institute of Management Studies & Research - Mumbai",
"Hamilton College",
"Hamline University",
"Hampden-Sydney College",
"Hampshire College",
"Hampton University",
"Hanover College",
"Harding University",
"Hartwick College",
"Harvard University",
"Harvey Mudd College",
"Haskell Indian Nations University",
"Hastings College",
"Haverford College in Pennsylvania",
"Hawaii Pacific University",
"HEC Paris",
"Heidelberg College",
"Hendrix College",
"Hesston College",
"High Point University",
"Hillsdale College",
"Hindustan Institute of Management and Computer Studies - Mathura",
"Hindustan Institute of Technology and Management  - Agra",
"Hirachand Nemchand College of Commerce  - Solapur",
"Hiram College",
"HK Institute of Management Studies and Research  - Mumbai",
"HKUST",
"Hobart and William Smith Colleges",
"Hofstra University",
"Hollins College",
"Holy Cross College",
"Holy Mary Business School  - Hyderabad",
"Hood College",
"Hope College",
"Howard University",
"Hult University",
"Humboldt State University",
"Hunter College",
"Huntingdon College",
"Huntington College",
"Hyderabad Central University - Hyderabad",
"ICBM School of Business Excellence  - Hyderabad",
"ICFAI Business School - Hyderabad",
"ICFAI Business School - Jaipur",
"ICFAI Business School - Kolkata",
"ICFAI Business School - Mumbai",
"ICFAI Business School - Pune",
"ICFAI Business School(IBS) - Ahmedabad",
"ICI University",
"Idaho State University",
"IE Business School",
"IEC Business School  - Noida",
"IESE Business School",
"IIKM Business School - Chennai",
"IILM Academy of Higher Learning  - Jaipur",
"IILM Graduate School of Management - Greater Noida",
"IILM Institute of Higher Education - New Delhi",
"IIMT College of Management  - Noida",
"IIMT Management College - Meerut",
"Illinois Benedictine College",
"Illinois Institute of Technology",
"Illinois State University",
"IMD Business School",
"Imperial College Business School",
"Imperial College of Business Studies  - Bangalore",
"IMS Unison University - Dehradun",
"INCAE Business School",
"Incarnate Word College",
"Indian Institute of Engineering Science and Technology  - Shibpur",
"Indian Institute of Foreign Trade - Kolkata",
"Indian Institute of Foreign Trade - New Delhi",
"Indian Institute of Forest Management - Bhopal",
"Indian Institute of Management - Amritsar",
"Indian Institute of Management - Bodh Gaya",
"Indian Institute of Management - Jammu",
"Indian Institute of Management - Nagpur",
"Indian Institute of Management - Sambalpur",
"Indian Institute of Management - Sirmaur",
"Indian Institute of Management - Visakhapatnam",
"Indian Institute of Management Ahmedabad",
"Indian Institute of Management Bangalore",
"Indian Institute of Management Calcutta",
"Indian Institute of Management Calcutta",
"Indian Institute of Management Indore",
"Indian Institute of Management Indore - Mumbai campus",
"Indian Institute of Management Kashipur",
"Indian Institute of Management Kozhikode",
"Indian Institute of Management Lucknow",
"Indian Institute of Management Raipur",
"Indian Institute of Management Ranchi",
"Indian Institute of Management Rohtak",
"Indian Institute of Management Shillong",
"Indian Institute of Management Trichy",
"Indian Institute of Management Udaipur",
"Indian Institute of Social Welfare & Business Management. - Kolkata",
"Indian School of Business ",
"Indian School of Mines - Dhanbad",
"Indiana Institute of Technology",
"Indiana State University",
"Indiana University - Bloomington",
"Indiana University - Pennsylvania",
"Indiana University - South Bend",
"Indiana University Southeast - New Albany",
"Indiana University System",
"Indiana University/Purdue University at Columbus",
"Indiana University/Purdue University at Fort Wayne",
"Indiana University/Purdue University at Indianapolis",
"Indiana Wesleyan University - Marion",
"Indira Global Business School - Pune",
"Indira Institute of Management  - Pune",
"Indirapuram Institute of Higher Studies - Ghaziabad",
"Indus Business Academy - Bangalore",
"Indus Business School - Pune",
"INSEAD",
"Institute for Financial Management and Research - Chennai",
"Institute For Technology and Management - Bangalore",
"Institute For Technology and Management - Chennai",
"Institute of Agribusiness Management - Noida",
"Institute of Business and Computer Studies - Bhubaneswar",
"Institute of Business Management & Research - IPS Academy - Indore",
"Institute of Business Management & Rural Development - Ahmednagar",
"Institute of Business Studies and Research  - Mumbai",
"Institute of Computers and Business Management - School of Business Excellence - Hyderabad",
"Institute of Engineering & Management - Kolkata",
"Institute of Engineering and Technology - Alwar",
"Institute of Excellence in Management Science - Hubli",
"Institute of Finance and International Management - Bangalore",
"Institute of Integrated Communication & Management  - Delhi",
"Institute of Logistics & Aviation Management  - Delhi",
"Institute of Management and Information Science - Bhubaneswar",
"Institute of Management and Technology - Faridabad",
"Institute of Management Development & Research  - Pune",
"Institute of Management Education  - Ghaziabad",
"Institute of Management Research and Technology  - Lucknow",
"Institute of Management Studies - Ahmednagar",
"Institute of Management Studies - Ghaziabad",
"Institute of Management Studies - Noida",
"Institute of Management Technology - Ghaziabad",
"Institute of Management Technology - Hyderabad",
"Institute of Management Technology - Nagpur",
"Institute of Marketing & Management - Delhi",
"Institute of Productivity & Management  - Meerut",
"Institute of Public Enterprise - Hyderabad",
"Institute of Rural Management - Anand",
"Institute of Rural Management - Jaipur",
"Institute of Technology & Science - Ghaziabad",
"Integral Institute of Advanced Management - Visakhapatnam",
"Inter American University of Puerto Rico Metropolitan Campus",
"International Institute of Business Studies  - Bangalore",
"International Institute of Business Studies  - Kolkata",
"International Institute of Learning and Management - Gurgaon",
"International Institute of Management Studies - Pune",
"International Management Institute - New Delhi",
"International School of Business & Media - Pune",
"International School of Business & Research - Bangalore",
"International School of Business & Research - Chennai",
"International School of Informatics & Management - Jaipur",
"International School of Management Excellence - Bangalore",
"International School of Telecom Technology and Management - Hyderabad",
"Iona College",
"Iowa State University",
"Ipade Business School",
"Ishan Institute of Management & Technology  - Noida",
"ITERC College of Management  - Ghaziabad",
"Ithaca College",
"ITM Business School - Bangalore",
"ITM Business School - Chennai",
"ITM Business School - Mumbai",
"ITM Business School - Navi Mumbai",
"ITM Business School - Noida",
"ITM Business School - Warangal",
"ITM Global Leadership Centre - Mumbai",
"ITM Institute of Financial Markets - Mumbai",
"ITS Institute of Management - Noida",
"ITS Management & IT Institute - Ghaziabad",
"Jackson State University",
"Jacksonville State University",
"Jacksonville University",
"Jagan Institute of Management Studies  - Delhi",
"Jagannath International Management School - Delhi",
"Jagran Institute of Communication and Management  - Bhopal",
"Jaipuria Institute of Management  - Ghaziabad",
"Jaipuria Institute of Management - Jaipur",
"Jaipuria Institute of Management - Noida",
"James Madison University",
"Jamestown College",
"Jamnalal Bajaj Institute of Management Studies - Mumbai",
"Jawaharlal Nehru National College of Engineering - Shimoga",
"Jayawant Institute of Management Studies  - Pune",
"Jindal Global Business School  - Sonepat",
"JK Business School - Gurgaon",
"JK Lakshmipat University  - Jaipur",
"JK Padampat Singhania Institute of Management & Technology  - Gurgaon",
"JKS Hegde Institute of Management  - Mangalore",
"John Brown University",
"John Carroll University",
"John F. Kennedy University",
"Johns Hopkins University",
"Johnson and Wales University",
"Johnson and Wales University - Charleston",
"Johnson Bible College",
"Johnson C. Smith University",
"Jones College",
"JRE School of Management - Greater Noida ",
"JSN School of Management  - Orikkai",
"Judson College",
"Juniata College",
"K. J. Somaiya Institute of Management Studies and Research - Mumbai",
"Kalamazoo College",
"Kanpur Institute of Technology - Kanpur",
"Kansas State University",
"Kansas Wesleyan University",
"Karunya School of Business Leadership and Management - Coimbatore",
"Kautilya Institute of Management and Research  - Pune",
"KCE Society's Institute of Management & Research  - Jalgaon",
"Kean College",
"Keene State College",
"Kent State University",
"Kenyon College",
"KIIT School of Management  - Bhubaneswar",
"King's College",
"Kirloskar Institute of Advanced Management Studies -Pune",
"KLS' Institute of Management Education and Research - Belgaum",
"Knox College",
"Koneru Lakshmaiah University - Guntur",
"Kongu Engineering College - Erode",
"KPR School of Business - Coimbatore",
"Kristu Jayanti College of Management and Technology - Bangalore",
"Kutztown University of Pennsylvania",
"La Sierra University",
"Lafayette College",
"LaGrange College",
"Lake Forest College",
"Lake Superior State University",
"Lal Bahadur Shastri Institute of Management - New Delhi",
"Lala Lajpatrai Institute of Management  - Mumbai",
"Lamar University",
"Lancaster University - Lancaster University Management School",
"Langston University",
"LaSalle University",
"Lawrence Technological University",
"Lawrence University",
"Le Moyne College",
"Lebanon Valley College",
"Leeds University Business School",
"Lehigh University",
"Lenoir-Rhyne College",
"LeTourneau University",
"Lewis and Clark College",
"Lewis University",
"Lewis-Clark State College",
"Liberty University",
"Lincoln University ",
"Linfield College",
"LN Welingkar Institute of Management - Bangalore",
"Lock Haven University of Pennsylvania",
"Loma Linda University",
"London Business School",
"London School of Economics",
"Long Island University",
"Longwood College",
"Loras College",
"Lotus Business School - Pune",
"Louisiana College",
"Louisiana State University",
"Louisiana State University - Alexandria",
"Louisiana State University - Shreveport",
"Louisiana Tech University",
"Lovely Professional University - Jalander",
"Loyola College",
"Loyola Institute of Business Administration - Chennai",
"Loyola Marymount University",
"Loyola University - Chicago",
"Loyola University Maryland",
"Loyola University New Orleans",
"Luther College",
"Luther Seminary",
"Lycoming College",
"Lynchburg College",
"Lyndon State College",
"Lyon College",
"M.O.P Vaishnav College For Women - Chennai",
"Macalester College",
"Macquarie Graduate School of Management",
"Madan Mohan Malaviya University of Technology  - Gorakhpur",
"Maharaja Agrasen Institute of Management - Kurukshetra",
"Maharashtra Institute of Technology  - School of Business - Pune",
"Maharishi University of Management",
"Maine Maritime Academy",
"Malone College",
"MANAGE - Hyderabad",
"Management Development Institute - Gurgaon",
"Manchester Business School",
"Manchester University",
"Mangalmay Institute of Management & Technology - Noida",
"Manhattan College",
"Manipal Institute of Management - Manipal",
"Mankato State University",
"Mannheim Business School",
"Mansfield University of Pennsylvania",
"Mar Athanasios College For Advanced Studies - Tiruvalla",
"Maratha Mandir's Babasaheb Gawde Institute of Management Studies - Mumbai",
"Marietta College",
"Marist College",
"Marlboro College",
"Marquette University",
"Marshall University",
"Marwadi Education Foundation's Group of Institutions - Rajkot",
"Mary Baldwin College",
"Mary Washington College",
"Marymount College",
"Marymount University",
"Massachusetts Institute of Technology",
"Massachusetts Maritime Academy",
"Master School of Management - Meerut",
"MATS institute of Management and Entrepreneurship  - Bangalore",
"McGill University",
"McMurry University",
"McNeese State University",
"Measi Institute of Management - Chennai",
"Medical College of Georgia",
"Medical College of Wisconsin",
"Melbourne Business School",
"Mercer University",
"Mercyhurst College",
"Meredith College",
"MES - Advanced Institute of Management and Technology - Ernakulam",
"Messiah College",
"MET Institute of Management - Mumbai",
"Metropolitan State College of Denver",
"Metropolitan State University",
"Miami Christian University",
"Miami University of Ohio",
"Michigan State University",
"Michigan Technological University",
"Mid-America Nazarene College",
"Middle Georgia College",
"Middle Tennessee State University",
"Middlebury College",
"Midwestern State University",
"Millennium School of Business  - Delhi",
"Millersville University of Pennsylvania",
"Milligan College",
"Millikin University",
"Mills College",
"Millsaps College",
"Milwaukee School of Engineering",
"Minneapolis College of Art and Design",
"Minot State University",
"Mississippi College",
"Mississippi State University",
"Mississippi University for Women",
"Missouri Southern State College",
"Missouri University of Science & Technology",
"Missouri Western State College",
"MIT School of Telecom Management - Pune",
"MM Institute of Management - Ambala",
"Molloy College",
"Monmouth College",
"Monmouth University",
"Montana State University - Billings",
"Montana State University - Bozeman",
"Montana State University - Northern",
"Montana Tech",
"Montclair State University",
"Montreat College",
"Moorhead State University",
"Moravian College",
"Morehouse College",
"Morgan State University",
"Motilal Nehru National Institute of Technology  - Allahabad",
"Mount Holyoke College",
"Mount Saint Joseph College",
"Mount Saint Mary College",
"Mount Senario College",
"Mount Union College",
"MS Ramaiah Institute of Management - Bangalore",
"MSNM Besant Institute of Post Graduate Studies  - Mangalore",
"Mudra Institute of Communications - Ahmedabad",
"Murray State University",
"Muskingum College",
"Nanyang Business School ",
"Nanyang Technological University",
"Narsee Monjee Institute of Management Studies - Bengaluru",
"Narsee Monjee Institute of Management Studies - Hyderabad",
"Narsee Monjee Institute of Management Studies - Mumbai",
"National Defense University",
"National Institute Of Fashion Technology - Delhi ",
"National Institute of Industrial Engineering - Mumbai",
"National Institute of Securities Markets - Mumbai ",
"National Institute of Technology - Durgapur",
"National Institute of Technology - Kurukshetra",
"National Institute of Technology - Tiruchirappalli",
"National Louis University",
"National Management School - Chennai ",
"National Technological University",
"National University",
"National University of Singapore",
"Naval Postgraduate School",
"Nazareth College",
"Nebraska Wesleyan University",
"Nehru College of Management - Coimbatore",
"New College of California",
"New England Institute of Technology",
"New Hampshire College",
"New Jersey Institute of Technology",
"New Mexico Highlands University",
"New Mexico Institute of Mining & Technology",
"New Mexico State University",
"New York Institute of Technology",
"New York University",
"Newberry College",
"Niagara University",
"Nicholls State University",
"NIET Business School - Noida",
"Nirma University Institute of Management - Ahmedabad",
"Norfolk State University",
"North Adams State College",
"North Carolina A&T State University",
"North Carolina Central University",
"North Carolina State University",
"North Carolina Wesleyan College",
"North Central Bible College",
"North Central College",
"North Dakota State University",
"North Park College and Theological Seminary",
"Northeastern Illinois University",
"Northeastern Louisiana University",
"Northeastern State University",
"Northeastern University",
"Northern Arizona University",
"Northern Illinois University",
"Northern Kentucky University",
"Northern Michigan University",
"Northern State University",
"Northland College",
"Northwest Missouri State University",
"Northwest Nazarene College",
"Northwestern College of Iowa",
"Northwestern State University",
"Northwestern University",
"Norwich University",
"Nova Southeastern University",
"NUS - Faculty of Engineering",
"NUS - Faculty of Law",
"Oakland University",
"Oberlin College",
"Occidental College",
"Ohio Dominican College",
"Ohio Northern University",
"Ohio State University - Columbus",
"Ohio State University - Marion",
"Ohio University - Athens",
"Ohio Wesleyan University",
"Oklahoma Baptist University",
"Oklahoma Christian University",
"Oklahoma City University",
"Oklahoma State University",
"Old Dominion University",
"Olivet Nazarene University",
"Om Kothari Institute of Management & Research - Kota",
"Oral Roberts University",
"Oregon Graduate Institute of Science and Technology",
"Oregon Health Sciences University",
"Oregon Institute of Technology",
"Oregon State University",
"Otterbein College",
"Otterbein University",
"Our Lady of the Lake University",
"Pace University",
"Pacific Institute of Management - Udaipur",
"Pacific Lutheran University",
"Pacific Union College",
"Pacific University",
"Pacific Western University ",
"Padmashree Dr. D.Y. Patil Institute of Management Studies - Pune",
"Palm Beach Atlantic College",
"Park's College - Tirupur",
"Patel Group of Institutions - Indore",
"Peace College",
"Pembroke State University",
"Pennsylvania State System of Higher Education",
"Pennsylvania State University",
"Pennsylvania State University - Schuylkill Campus",
"Pensacola Christian College",
"People's Institute of Management - Bhopal",
"Pepperdine University",
"Peru State College",
"PES Institute of Technology - Department of MBA - Bangalore",
"Philadelphia College of Textiles and Science",
"Phillips University",
"Pittsburg State University",
"Pitzer College",
"Platt College",
"Plymouth State College",
"Point Loma Nazarene College",
"Polytechnic University of New York",
"Polytechnic University of Puerto Rico",
"Pomona College",
"Portland State University",
"Pragati Mahavidyalaya PG College - Hyderabad",
"Prairie View A&M University",
"Pratt Institute",
"Presbyterian College",
"Prescott College",
"Presidency College - Bangalore",
"Prestige Institute of Management - Dewas",
"Prestige Institute of Management - Gwalior",
"Prin. L. N. Welingkar Institute of Management Development & Research - Mumbai",
"Princeton University",
"Providence College",
"PSNA College of Engineering and Technology - Dindigul",
"Pune Institute of Business Management - Pune ",
"Punjab College of Technical Education - Ludhiana",
"Purdue University",
"Purdue University - Calumet",
"Purdue University - North Central",
"Queen's University",
"Quincy University",
"Quinnipiac College",
"Quinnipiac University",
"Radford University",
"Rajasthan Institute of Engineering and Technology - Jaipur",
"Rajiv Gandhi Business School - Pune",
"Ramapo College",
"Randolph-Macon College",
"Randolph-Macon Woman's College",
"Reed College",
"Regent University",
"Regis University",
"Renmin University of China",
"Rensselaer Polytechnic Institute",
"Rhode Island College",
"Rhodes College",
"Rice University",
"Richard Stockton College of New Jersey",
"Rider University",
"Ripon College",
"Rivier College",
"Roanoke College",
"Rochester Institute of Technology",
"Rockford College",
"Rockhurst College",
"Rockhurst University",
"Rocky Mountain College",
"Roger Williams University",
"Rollins College",
"Rosary College",
"Rose-Hulman Institute of Technology",
"Rotterdam School of Management",
"Rowan College",
"Rowan University",
"Rungta College of Engineering and Technology - Bhilai",
"Rutgers University",
"RV Institute of Management - Bangalore",
"RVS Institute of Management Studies & Research - Coimbatore",
"S. P. Jain Institute of Management & Research - Mumbai",
"Sacred Heart University (CT)",
"Sacred Heart University (PR)",
"Sadhana Centre for Management & Leadership Development - Pune",
"Saginaw Valley State University",
"Sai Institute of Management - Amritsar",
"Saint Anselm College",
"Saint Catherine University",
"Saint Cloud State University",
"Saint Edward's University",
"Saint Francis College",
"Saint John's University (MN)",
"Saint John's University (NY)",
"Saint Joseph's College (IN)",
"Saint Joseph's University",
"Saint Louis University",
"Saint Mary College",
"Saint Mary's College (IN)",
"Saint Mary's College of California",
"Saint Mary's University of Minnesota",
"Saint Michael's College",
"Saint Olaf College",
"Saint Vincent College",
"Saint Xavier University",
"Saintgits Institute of Management - Kottayam",
"Salisbury State University",
"Salish Kootenai College",
"Sam Houston State University",
"Samalkha Group of Institutions - Panipat",
"Sambhram Academy of Management Studies - Bangalore",
"Samford University",
"San Diego State University",
"San Francisco State University",
"San Jose State University",
"Sanskriti School of Business - Mathura",
"Santa Clara University",
"Sarah Lawrence College",
"Sardar Vallabhbhai Patel International School of Textiles and Management - Coimbatore",
"School of Business Studies - Sharda University",
"School of Inspired Leadership - Gurgaon ",
"School of Management - Hindustan Institute of Technology and Science - Chennai",
"School of Management - International Institute of Management - Bhubaneswar",
"School of the Art Institute of Chicago",
"SCMS School of Technology and Management - Kochi",
"SDA Bocconi",
"SDM Institute for Management Development - Mysore ",
"Seattle Pacific University",
"Seattle University",
"Sengunthar Institute of Management - Tiruchengode",
"Seshadripuram Institute of Management Studies - Bangalore ",
"Seton Hall University",
"Sewanee - University of the South",
"Shailesh J. Mehta School of Management - Indian Institute of Technology Bombay",
"Shanghai Jiao Tong University",
"Shanti Business School  - Ahmedabad",
"Shawnee State University",
"Shenandoah University",
"Shippensburg University of Pennsylvania",
"Shorter College",
"Shreeyash Institute of Management - Aurangabad",
"Shri Dharmasthala Manjunatheshwara Institute for Management Development - Mysore",
"Simmons College",
"Simon's Rock College",
"Simpson College",
"Sinhgad Institute of Business Administration and Research - Pune",
"Sinhgad Institute of Management - Pune",
"Siva Sivani Institute of Management - Hyderabad",
"Skidmore College",
"Slippery Rock University of Pennsylvania",
"Smith College",
"SNS College of Engineering - Coimbatore",
"SNS College of Technology - Coimbatore",
"Sona School of Management - Salem",
"Sonoma State University",
"South Dakota School of Mines and Technology",
"South Dakota State University",
"South Texas College of Law",
"Southampton College",
"Southeast Missouri State University",
"Southeastern Louisiana University",
"Southern College",
"Southern College of Technology",
"Southern Connecticut State University",
"Southern Illinois University",
"Southern Illinois University - Carbondale",
"Southern Illinois University - Edwardsville",
"Southern Methodist University",
"Southern Nazarene University",
"Southern Oregon State College",
"Southern University",
"Southern Utah University",
"Southwest Baptist University",
"Southwest Missouri State University",
"Southwest State University",
"Southwest Texas State University",
"Southwestern Adventist College",
"Southwestern University",
"Spelman College",
"Spring Arbor College",
"Spring Hill College",
"Sri Sairam Institute of Management Studies - Chennai",
"SRM School of Management - Chennai",
"SSM School of Management - Namakkal",
"St Aloysius Institute of Management & Information Technology - Mangalore",
"St. Ambrose University",
"St. Andrews Presbyterian College",
"St. Bonaventure University",
"St. John's College - Annapolis",
"St. John's College - Santa Fe",
"St. Joseph College (CT)",
"St. Joseph's College (ME)",
"St. Joseph's Degree & PG College - Hyderabad",
"St. Lawrence University",
"St. Louis College of Pharmacy",
"St. Martin's College",
"St. Thomas University (FL)",
"Stanford University",
"State University of New York at Albany",
"State University of New York at Binghamton",
"State University of New York at Buffalo",
"State University of New York at Farmingdale",
"State University of New York at Fredonia",
"State University of New York at Oswego",
"State University of New York at Plattsburgh",
"State University of New York at Stony Brook",
"State University of New York College at Brockport",
"State University of New York College at Buffalo (Buffalo State College)",
"State University of New York College at Cortland",
"State University of New York College at Geneseo",
"State University of New York College at New Paltz",
"State University of New York College at Oneonta",
"State University of New York College at Potsdam",
"State University of New York College of Agriculture and Technology at Cobleskill",
"State University of New York College of Environmental Science and Forestry",
"State University of New York College of Technology at Alfred",
"State University of New York Institute of Technology at Utica/Rome",
"State University of New York Polytechnic Institute",
"State University of New York System",
"Stephen F. Austin State University",
"Stephens College",
"Stetson University",
"Stevens Institute of Technology",
"Strayer College",
"Suffolk University",
"Sul Ross State University",
"Summit University of Louisiana",
"Sungkyunkwan University GSB",
"Suryadatta Institute of Management & Mass Communication - Pune",
"Susquehanna University",
"SV Institute of Management - Kadi",
"Swarthmore College",
"Sweet Briar College",
"Sydenham Institute of Management Studies and Research and Entrepreneurship Education - Mumbai",
"Symbiosis Centre for Management and Human Resource Development - Pune",
"Symbiosis Institute of Business Management - Bengaluru",
"Symbiosis Institute of Business Management - Pune",
"Symbiosis Institute of Computer Studies and Research - Pune",
"Symbiosis Institute of Information Technology  - Pune",
"Symbiosis Institute of International Business - Pune",
"Symbiosis Institute of Management Studies - Pune",
"Symbiosis Institute of Operations Management  - Nashik",
"Symbiosis Institute of Telecom Management - Pune",
"Syracuse University",
"T. A. Pai Management Institute - Manipal",
"Tabor College",
"Tarleton State University",
"Tata Institute of Social Sciences - Mumbai",
"Taxila Business School - Jaipur",
"Taylor University",
"Teachers College - Columbia University",
"Techno Institute of Management Sciences - Lucknow",
"Tecnia Institute of Advanced Studies - Delhi",
"Teerthanker Mahaveer Institute of Management & Technology - Moradabad",
"Teikyo Marycrest University",
"Temple University",
"Tennessee State University",
"Tennessee Technological University",
"Texas A&M International University",
"Texas A&M University - College Station",
"Texas A&M University - Corpus Christi",
"Texas A&M University - Kingsville",
"Texas Christian University",
"Texas Southern University",
"Texas Tech University",
"Texas Tech University - Health Sciences Center",
"Texas Woman's University",
"The Catholic University of America",
"The Chicago School of Professional Psychology",
"The Citadel",
"The College of Wooster",
"The Cooper Union for the Advancement of Science and Art",
"The Jewish Theological Seminary",
"The Lisbon MBA",
"The Oxford College of Engineering - Bangalore",
"The Rockefeller University",
"The Sage Colleges",
"The Uniformed Services University of the Health Sciences",
"The Union Institute",
"Thiagarajar School of Management - Madurai",
"Thomas College",
"Thomas Edison State College",
"Thomas Jefferson University",
"Thomas More College",
"TIAS School for Business and Society",
"Tilak Raj Chadha Institute of Management & Technology - Yamunanagar",
"Towson State University",
"Transylvania University",
"Trenton State College",
"Trinity College (CT)",
"Trinity College (DC)",
"Trinity University",
"Troy State University",
"Truman State University",
"Tucson University",
"Tufts University",
"Tulane University",
"Tula's Institute - Dehradun",
"Tuskegee University",
"Union College",
"Union University",
"United States Air Force Academy",
"United States International University",
"United States Merchant Marine Academy",
"United States Military Academy",
"United States Naval Academy",
"University Business School - Punjab University - Chandigarh",
"University College Dublin: Smurfit",
"University of Akron",
"University of Alabama - Birmingham",
"University of Alabama - Huntsville",
"University of Alabama - Tuscaloosa",
"University of Alaska",
"University of Alaska - Anchorage",
"University of Alaska - Fairbanks",
"University of Alaska - Southeast",
"University of Alberta",
"University of Arizona",
"University of Arkansas - Fayetteville",
"University of Arkansas - Little Rock",
"University of Arkansas - Monticello",
"University of Arkansas for Medical Sciences",
"University of Baltimore",
"University of Bath - School of Management",
"University of Bridgeport",
"University of British Columbia",
"University of California - Berkeley",
"University of California - Davis",
"University of California - Irvine",
"University of California - Los Angeles",
"University of California - Riverside",
"University of California - San Diego",
"University of California - San Francisco",
"University of California - Santa Barbara",
"University of California - Santa Cruz",
"University of Cambridge",
"University of Cape Town",
"University of Central Arkansas",
"University of Central Florida",
"University of Central Texas",
"University of Charleston",
"University of Chicago",
"University of Cincinnati",
"University of Colorado - Boulder",
"University of Colorado - Colorado Springs",
"University of Colorado - Denver",
"University of Colorado Health Sciences Center",
"University of Connecticut",
"University of Dallas",
"University of Dayton",
"University of Delaware",
"University of Denver",
"University of Detroit Mercy",
"University of Dubuque",
"University of Edinburgh Business School",
"University of Evansville",
"University of Florida",
"University of Georgia",
"University of Great Falls",
"University of Guam",
"University of Hartford",
"University of Hawaii - Hilo Physics and Astronomy",
"University of Hawaii - Manoa",
"University of Hong Kong",
"University of Houston",
"University of Idaho",
"University of Ilinois - Urbana-Champaign",
"University of Illinois - Chicago",
"University of Illinois - Springfield",
"University of Illinois - Urbana-Champaign",
"University of Indianapolis",
"University of Iowa",
"University of Kansas",
"University of Kansas School of Medicine",
"University of Kentucky",
"University of La Verne",
"University of Louisville",
"University of Maine",
"University of Maine - Farmington",
"University of Maine - Fort Kent",
"University of Maine - Machias",
"University of Maine - Presque Island",
"University of Maine System",
"University of Mary Washington",
"University of Maryland - Baltimore",
"University of Maryland - Baltimore County",
"University of Maryland - College Park",
"University of Maryland - University College",
"University of Massachusetts - Amherst",
"University of Massachusetts - Dartmouth",
"University of Massachusetts - Lowell",
"University of Massachusetts System",
"University of Memphis",
"University of Miami",
"University of Michigan - Ann Arbor",
"University of Michigan - Dearborn",
"University of Minnesota",
"University of Minnesota - Crookston",
"University of Minnesota - Duluth",
"University of Minnesota - Morris",
"University of Minnesota - Twin Cities",
"University of Mississippi",
"University of Mississippi Medical Center",
"University of Missouri - Columbia",
"University of Missouri - Kansas City",
"University of Missouri - Rolla",
"University of Missouri - Saint Louis",
"University of Montana",
"University of Nebraska - Kearney",
"University of Nebraska - Lincoln",
"University of Nebraska - Omaha",
"University of Nevada - Las Vegas",
"University of Nevada - Reno",
"University of New England",
"University of New Hampshire - Durham",
"University of New Haven",
"University of New Mexico",
"University of New Orleans",
"University of North Carolina - Asheville",
"University of North Carolina - Chapel Hill",
"University of North Carolina - Charlotte",
"University of North Carolina - Greensboro",
"University of North Carolina - Wilmington",
"University of North Carolina System",
"University of North Dakota",
"University of North Florida",
"University of North Texas",
"University of North Texas Health Science Center",
"University of Northern Colorado",
"University of Northern Iowa",
"University of Notre Dame",
"University of Oklahoma",
"University of Oregon",
"University of Oxford",
"University of Pennsylvania",
"University of Phoenix",
"University of Pittsburgh",
"University of Pittsburgh - Johnstown",
"University of Portland",
"University of Puerto Rico",
"University of Puget Sound",
"University of Redlands",
"University of Rhode Island",
"University of Richmond",
"University of Rochester",
"University of Saint Thomas",
"University of Saint Thomas (MN)",
"University of San Diego",
"University of San Francisco",
"University of Sarasota",
"University of Science & Arts of Oklahoma",
"University of Scranton",
"University of Sioux Falls",
"University of South Alabama",
"University of South Carolina",
"University of South Carolina - Aiken",
"University of South Dakota",
"University of South Florida",
"University of Southern California",
"University of Southern Colorado",
"University of Southern Indiana",
"University of Southern Maine",
"University of Southern Mississippi",
"University of Southwestern Louisiana",
"University of St Gallen",
"University of Strathclyde",
"University of Tampa",
"University of Tennessee - Knoxville",
"University of Tennessee - Martin",
"University of Texas  - Pan American",
"University of Texas - Arlington",
"University of Texas - Austin",
"University of Texas - Brownsville",
"University of Texas - Dallas",
"University of Texas - El Paso",
"University of Texas - San Antonio",
"University of Texas - Tyler",
"University of Texas Health Center - Tyler",
"University of Texas Health Science Center - Houston",
"University of Texas Health Science Center - San Antonio",
"University of Texas M.D. Anderson Cancer Center",
"University of Texas Medical Branch",
"University of Texas Southwestern Medical Center - Dallas",
"University of Texas System",
"University of the District of Columbia",
"University of the Ozarks",
"University of the Pacific",
"University of the Virgin Islands",
"University of Toledo",
"University of Toronto",
"University of Tulsa",
"University of Utah",
"University of Vermont",
"University of Virginia",
"University of Virginia - Charlottesville",
"University of Washington",
"University of West Alabama",
"University of West Florida",
"University of Wisconsin - Eau Claire",
"University of Wisconsin - Green Bay",
"University of Wisconsin - LaCrosse",
"University of Wisconsin - Madison",
"University of Wisconsin - Milwaukee",
"University of Wisconsin - Oshkosh",
"University of Wisconsin - Parkside",
"University of Wisconsin - Platteville",
"University of Wisconsin - River Falls",
"University of Wisconsin - Stevens Point",
"University of Wisconsin - Stout",
"University of Wisconsin - Superior",
"University of Wisconsin - Whitewater",
"University of Wisconsin System",
"University of Wyoming",
"Upper Iowa University",
"Ursinus College",
"Ursuline College",
"Utah State University",
"Utah Valley State College",
"V.S.B. Engineering College - Karur",
"Valdosta State University",
"Valley City State University",
"Valparaiso University",
"Vanderbilt University",
"Vanguard Business School - Bangalore",
"Vassar College",
"Vedatya Institute - Gurgaon",
"Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunthala Engineering College - Chennai",
"Vermont Technical College",
"Vidyasagar Institute of Management - Bhopal",
"Villa Julie College",
"Villanova University",
"Vinod Gupta School of Management - Indian Institute of Technology Kharagpur",
"Virginia Commonwealth University",
"Virginia Intermont College",
"Virginia Military Institute",
"Virginia Polytechnic Institute and State University",
"Virginia State University",
"Virginia Wesleyan College",
"Vlerick Business School",
"Wabash College",
"Wake Forest University",
"Walden University",
"Walla Walla College",
"Warangal Institute of Management - Warangal",
"Warren Wilson College",
"Wartburg College",
"Warwick Business School",
"Washburn University",
"Washington and Lee University",
"Washington Bible College/Capital Bible Seminary",
"Washington College",
"Washington State University",
"Washington State University - Tri-Cities",
"Washington State University - Vancouver",
"Washington University",
"Washington University at Saint Louis",
"Wayne State University",
"Waynesburg College",
"Weber State University",
"Webster University",
"Wellesley College",
"Wells College",
"Wentworth Institute of Technology",
"Wesley College",
"Wesleyan University",
"West Chester University of Pennsylvania",
"West Coast University",
"West Georgia College",
"West Liberty State College",
"West Texas A&M University",
"West Virginia University",
"West Virginia University - Parkersburg",
"Western Carolina University",
"Western Connecticut State University",
"Western Illinois University",
"Western Kentucky University",
"Western Maryland College",
"Western Michigan University",
"Western Montana College",
"Western New England College",
"Western New Mexico University",
"Western State College",
"Western University",
"Western Washington University",
"Westfield State College",
"Westminster College",
"Westminster College of Salt Lake City",
"Westminster Theological Seminary",
"Westmont College",
"Wheaton College",
"Wheaton College - Norton MA",
"Wheeling Jesuit College",
"Whitman College",
"Whittier College",
"Whitworth College",
"Whitworth University",
"Wichita State University",
"Widener University",
"Wilberforce University",
"Wilkes University",
"Willamette University",
"William Howard Taft University",
"William Jewell College",
"William Mitchell College of Law",
"William Paterson College",
"William Penn College",
"William Woods University",
"Williams College",
"Wilmington College",
"Winona State University",
"Winthrop University",
"Wittenberg University",
"Wofford College",
"Woodbury University",
"Worcester Polytechnic Institute",
"Wright State University",
"Xavier Institute of Management - Bhubaneswar",
"Xavier School of Management - Jamshedpur",
"Xavier University",
"Xavier University of Louisiana",
"Yale University",
"Yeshiva University",
"York College of Pennsylvania",
"York University",
"Youngstown State University"
]
end
end